### ISSUE TITLE
Add a countdown effect

### ISSUE THREAD

**Issue by atharva434** [atharva434/INCF-Impact-visualization-Portal#19]
In the home page the impact count is getting displayed as for eg "5 million". These tiles need to have countdown animation as in the numbers should go from 1-2-3 to actual count. I ll really appreciate if anybody with js knowledge can look into it.

**Comment by glitcher007** [comment]
Hi @atharva434 

I hope this message finds you well. I'm writing to express my keen interest in the task you mentioned recently. Given my background and skill set, I believe I'm well-equipped to handle the requirements effectively.

Here are the skills I possess that align with the task:

Proficiency in JavaScript, HTML, CSS, and frameworks like React and D3.js for creating interactive and visually appealing data visualizations.
Experience in web development, encompassing both front-end and back-end development practices.
Strong attention to detail in user interface design and user experience optimization.
Effective communication and collaboration skills, which are essential for working closely with stakeholders to ensure project success.
I am genuinely excited about the opportunity to contribute to this task and am eager to get started. Please consider assigning me to this project, and I'll ensure we achieve our objectives efficiently.

Looking forward to your response.

**Comment by atharva434** [comment]
Hey I have assigned you the task.

**Comment by glitcher007** [comment]
Hi @atharva434 
![Screenshot (129)](https://github.com/atharva434/INCF-Impact-visualization-Portal/assets/112776999/2b0bdb2e-44f9-4041-a048-f42bbe717b42)
![Screenshot (130)](https://github.com/atharva434/INCF-Impact-visualization-Portal/assets/112776999/469676f7-4dd3-43cd-9431-aa095490bb05)

For reference I have added before and after the changes made
I hope this message finds you well. I'm excited to announce a new addition to our homepage that will enhance user engagement and visual appeal.

We've implemented a captivating Horizontal Countdown Animation on our homepage, designed to grab attention and provide a dynamic element to our interface. This animation features a series of flip digits that count up, creating a visually striking effect that adds a modern touch to our website.

The countdown animation serves multiple purposes, including:

Enhanced Visual Experience: The dynamic animation captures users' attention and adds a touch of interactivity to our homepage, making the browsing experience more enjoyable.

Highlighting Time-sensitive Content: By incorporating the countdown, we can draw attention to time-sensitive events, promotions, or deadlines, ensuring that visitors are informed and engaged with our latest updates.

Technical Elegance: The implementation leverages modern web technologies such as CSS animations and JavaScript, demonstrating our commitment to technical excellence and innovation.

We believe that this addition will contribute positively to our website's overall user experience and reinforce our brand identity as forward-thinking and user-focused.

Furthermore, I'd like to express my interest in contributing to the chatbot part of our platform. Given my strong knowledge of language chains and their applications, I believe I can add value to our chatbot development efforts by leveraging this expertise effectively.

Please take a moment to explore the updated homepage and share any feedback or suggestions you may have. Your input is invaluable as we continue to refine and improve our online presence.

**Comment by surajgajul** [comment]
Sir, I would like to try this issue out. We have to add the countdown effect on homepage's impact numbers right? (epilepsy, etc.)

**Comment by atharva434** [comment]
Yes correct @surajgajul!

**Comment by glitcher007** [comment]
Hii @atharva434 
Sorry I misunderstood the task can i redo the task
I would love to contribute further to this project

**Comment by atharva434** [comment]
Yeah cool its okay all I am saying is if you don't get a clear idea about
the task you can ask again don't assume.

**Comment by atharva434** [comment]
Yess sure you can still do the task but I am asking did you understand the
task now or do you need clarification?

**Comment by glitcher007** [comment]
Sir can you please elaborate a bit 
do we need add a countdown of number of registrations?

**Comment by atharva434** [comment]
> Sir can you please elaborate a bit do we need add a countdown of number of registrations?

Hi sorry I got busy couldn't reply. Actually you tried making changes in the wrong html file.
